name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        # Обновление и установка необходимых инструментов
        sudo apt-get update
        sudo apt-get install -y \
          git \
          python3-pip \
          openjdk-17-jdk \
          unzip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libssl-dev \
          libc6-dev \
          libc6-dev-i386 \
          gcc-multilib \
          g++-multilib

        # Установка buildozer
        pip3 install --upgrade pip
        pip3 install buildozer

    - name: Build APK
      env:
        ANDROIDSDK: ${{ secrets.ANDROIDSDK }}
        ANDROIDNDK: ${{ secrets.ANDROIDNDK }}
      run: |
        # Пример сборки проекта с помощью buildozer
        # Перед запуском убедитесь, что ваш buildozer.spec настроен правильно
        buildozer android debug deploy run
